-- 코드를 입력하세요
SELECT distinct(CAR_RENTAL_COMPANY_CAR.CAR_ID) from CAR_RENTAL_COMPANY_CAR,CAR_RENTAL_COMPANY_RENTAL_HISTORY
where CAR_RENTAL_COMPANY_CAR.car_id=CAR_RENTAL_COMPANY_RENTAL_HISTORY.car_id
and CAR_RENTAL_COMPANY_CAR.CAR_TYPE='세단'
and to_char(CAR_RENTAL_COMPANY_RENTAL_HISTORY.START_DATE,'yyyy-mm-dd') like '%-10-%'
order by CAR_RENTAL_COMPANY_CAR.CAR_ID desc;
